<div class="article-container">
    
    <?php foreach($articles as $article): ?>
    
        <article class="post">
            
            <div class="post-head">
                <img src="public/uploads/profile_img/<?= $article['image_path'] = $article['image_path'] ?? 'default_profile.png'; ?>" alt="Photo de <?= htmlspecialchars($article['username']) ?>"></img>
                <div>
                    <a href="index.php?route=profile&user=<?= htmlspecialchars($article['username']) ?>"><p><?= htmlspecialchars($article['username']) ?></p></a>
                    <p><?= htmlspecialchars($article['time_stamp']) ?></p>
                </div>
            </div>
            
            <div class="post-content">
                <p><?= htmlspecialchars($article['content']) ?></p>
            </div>
            
            
            <div class="post-comments">
                <?php foreach($comments as $comment): ?>
                
                    <?php if($comment['article_id'] === $article['id']): ?>
                        
                        <div class="comment">
                            <div class="comment-head">
                                <p><a href="index.php?route=profile&user=<?= htmlspecialchars($comment['username']) ?>"><?= htmlspecialchars($comment['username']) ?></a></p>
                                <p>-<?= htmlspecialchars($comment['time_stamp']) ?></p>
                            </div>
                            
                            <p><?= htmlspecialchars($comment['content']) ?></p>
                        </div>
                        
                    <?php endif; ?>
                    
                <?php endforeach; ?>
                
            </div>
                <form method="post" action="index.php?route=dashboard&action=comment&id=<?= $article['id'] ?>">
                    <input 
                        type="hidden" 
                        name="article-token" 
                        value="<?php foreach($_SESSION['article-tokens'] as $entry):?><?php if($entry['id'] === $article['id']): ?><?=$entry['token'];?><?php endif; ?><?php endforeach; ?>">
                    <input type="hidden" name="article-id" value="<?= $article['id']; ?>">
                    <input type="text" name="comment" placeholder="Écrivez une réponse..."/>
                </form>
            
        </article>
        
    <?php endforeach; ?>
    
</div>