<div class="article-container">
    
    <?php foreach($articles as $article): ?>
    
        <article class="post">
            
            <div class="post-head">
                <div class="post-head-left">
                    <a href="index.php?route=profile&user=<?= htmlspecialchars($article['username']) ?>">
                        <img src="public/uploads/profile_img/<?= $article['image_path'] = $article['image_path'] ?? 'default_profile.png'; ?>" alt="Photo de <?= htmlspecialchars($article['username']) ?>"></img>
                    </a>
                    <div>
                        <a href="index.php?route=profile&user=<?= htmlspecialchars($article['username']) ?>"><p><?= htmlspecialchars($article['username']) ?></p></a>
                        <p><?= htmlspecialchars($article['time_stamp']) ?></p>
                    </div>
                </div>
                <div class="post-head-right">
                    <?php if($_SESSION['user_data']['username'] === $article['username'] || $_SESSION['user_data']['validate'] === 5): ?>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M170.5 51.6L151.5 80h145l-19-28.4c-1.5-2.2-4-3.6-6.7-3.6H177.1c-2.7 0-5.2 1.3-6.7 3.6zm147-26.6L354.2 80H368h48 8c13.3 0 24 10.7 24 24s-10.7 24-24 24h-8V432c0 44.2-35.8 80-80 80H112c-44.2 0-80-35.8-80-80V128H24c-13.3 0-24-10.7-24-24S10.7 80 24 80h8H80 93.8l36.7-55.1C140.9 9.4 158.4 0 177.1 0h93.7c18.7 0 36.2 9.4 46.6 24.9zM80 128V432c0 17.7 14.3 32 32 32H336c17.7 0 32-14.3 32-32V128H80zm80 64V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16z"/></svg>
                    <?php endif; ?>
                </div>
            </div>
            
            <div class="post-content">
                <p><?= htmlspecialchars($article['content']) ?></p>
            </div>
            
            
            <div class="post-comments">
                <?php foreach($comments as $comment): ?>
                
                    <?php if($comment['article_id'] === $article['id']): ?>
                        
                        <div class="comment-container">
                            <a href="index.php?route=profile&user=<?= htmlspecialchars($comment['username']) ?>">
                                <img src="public/uploads/profile_img/<?= $comment['image_path'] = $comment['image_path'] ?? 'default_profile.png'; ?>" alt="Photo de <?= htmlspecialchars($comment['username']) ?>"></img>
                            </a>
                            <div class="comment-sub-container">
                                <div class="comment">
                                    <div class="comment-head">
                                        <p><a href="index.php?route=profile&user=<?= htmlspecialchars($comment['username']) ?>"><?= htmlspecialchars($comment['username']) ?></a></p>
                                    </div>
                                    
                                    <p><?= htmlspecialchars($comment['content']) ?></p>
                                </div>
                                <time datetime="<?= htmlspecialchars($comment['time_stamp']) ?>"><?= htmlspecialchars($comment['time_stamp']) ?></time> 
                            </div>
                            <?php if($_SESSION['user_data']['username'] === $article['username'] || $_SESSION['user_data']['validate'] === 5): ?>
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M170.5 51.6L151.5 80h145l-19-28.4c-1.5-2.2-4-3.6-6.7-3.6H177.1c-2.7 0-5.2 1.3-6.7 3.6zm147-26.6L354.2 80H368h48 8c13.3 0 24 10.7 24 24s-10.7 24-24 24h-8V432c0 44.2-35.8 80-80 80H112c-44.2 0-80-35.8-80-80V128H24c-13.3 0-24-10.7-24-24S10.7 80 24 80h8H80 93.8l36.7-55.1C140.9 9.4 158.4 0 177.1 0h93.7c18.7 0 36.2 9.4 46.6 24.9zM80 128V432c0 17.7 14.3 32 32 32H336c17.7 0 32-14.3 32-32V128H80zm80 64V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16zm80 0V400c0 8.8-7.2 16-16 16s-16-7.2-16-16V192c0-8.8 7.2-16 16-16s16 7.2 16 16z"/></svg>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                    
                <?php endforeach; ?>
                
            </div>
                <form method="post" action="index.php?route=dashboard&action=comment&id=<?= $article['id'] ?>">
                    <input 
                        type="hidden" 
                        name="article-token" 
                        value="<?php foreach($_SESSION['article-tokens'] as $entry):?><?php if($entry['id'] === $article['id']): ?><?=$entry['token'];?><?php endif; ?><?php endforeach; ?>">
                    <input type="hidden" name="article-id" value="<?= $article['id']; ?>">
                    <input type="text" name="comment" placeholder="Écrivez une réponse..."/>
                </form>
            
        </article>
        
    <?php endforeach; ?>
    
</div>