<div class="article-container">
    
    <?php foreach($articles as $article): ?>
        <?php if($article['validate'] !== 0): ?>
                    
    
        <article class="post">
            
            <div class="post-head">
                <div class="post-head-left">
                    <a href="index.php?route=profile&user=<?= htmlspecialchars($article['username']) ?>">
                        <img src="public/uploads/profile_img/<?= $article['image_path'] = $article['image_path'] ?? 'default_profile.png'; ?>" alt="Photo de <?= htmlspecialchars($article['username']) ?>"></img>
                    </a>
                    <div>
                        <a href="index.php?route=profile&user=<?= htmlspecialchars($article['username']) ?>"><p><?= htmlspecialchars($article['username']) ?></p></a>
                        <p><?= htmlspecialchars($article['time_stamp']) ?></p>
                    </div>
                </div>
                <div class="post-head-right">
                    <?php if($_GET['route'] !== 'article'): ?>
                        <a href="index.php?route=article&id=<?= htmlspecialchars($article['id']) ?>">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" /></svg>
                        </a>
                    <?php endif; ?>
                    <?php if($_SESSION['user_data']['username'] === $article['username'] || $_SESSION['user_data']['validate'] === 5): ?>
                        <form method="post" action="index.php?route=dashboard&action=delete-article">
                            <input type="hidden" name="article-id" value="<?=$article['id'] ?>"/>
                            <input type="hidden" name="article-token" value="<?php foreach($_SESSION['article-tokens'] as $entry):?><?php if($entry['id'] === $article['id']): ?><?=$entry['token'];?><?php endif; ?><?php endforeach; ?>">
                            <button type="submit">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" /></svg>
                            </button>
                        </form>
                    <?php endif; ?>
                </div>
            </div>
            
            
            
                
            <div class="post-text">
                <p><?= htmlspecialchars($article['content']) ?></p>
            </div>
                
            <div class="post-media">
                <?php if($article['audio_file'] !== null): ?>
                    <audio controls <?php if($article['article_image'] !== null){ echo 'class="with-image"';} ?>>
                      <source src="public/uploads/audio_files/<?= htmlspecialchars($article['audio_file']) ?>" type="audio/mpeg">
                    </audio>
                <?php endif; ?>
                <?php if($article['article_image'] !== null): ?>
                    <img src="public/uploads/article_img/<?= htmlspecialchars($article['article_image']) ?>">
                    </img>
                <?php endif; ?>
                
            </div>
            
            <div class="post-comments">
                <?php foreach($comments as $comment): ?>
                
                    <?php if($comment['article_id'] === $article['id'] && $comment['validate']): ?>
                        
                        <div class="comment-container">
                            
                            <a href="index.php?route=profile&user=<?= htmlspecialchars($comment['username']) ?>">
                                <img src="public/uploads/profile_img/<?= $comment['image_path'] = $comment['image_path'] ?? 'default_profile.png'; ?>" alt="Photo de <?= htmlspecialchars($comment['username']) ?>"></img>
                            </a>
                            <div class="comment-sub-container">
                                <div class="comment">
                                    <div class="comment-head">
                                        <p><a href="index.php?route=profile&user=<?= htmlspecialchars($comment['username']) ?>"><?= htmlspecialchars($comment['username']) ?></a></p>
                                    </div>
                                    
                                    <p><?= htmlspecialchars($comment['content']) ?></p>
                                </div>
                                <time datetime="<?= htmlspecialchars($comment['time_stamp']) ?>"><?= htmlspecialchars($comment['time_stamp']) ?></time> 
                            </div>
                            
                            <?php if($_SESSION['user_data']['username'] === $article['username'] || $_SESSION['user_data']['username'] === $comment['username'] || $_SESSION['user_data']['validate'] === 5): ?>
                                
                                <form method="post" action="index.php?route=dashboard&action=delete-comment">
                                    <input type="hidden" name="comment-id" value="<?=$comment['id'] ?>"/>
                                    <input type="hidden" name="comment-token" value="<?php foreach($_SESSION['comment-tokens'] as $entry):?><?php if($entry['id'] === $comment['id']): ?><?=$entry['token'];?><?php endif; ?><?php endforeach; ?>">
                                    <button type="submit">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" /></svg>
                                    </button>
                                </form> 
                                
                            <?php endif; ?>
                            
                        </div>
                    <?php endif; ?>
                    
                <?php endforeach; ?>
                
            </div>
                <form method="post" action="index.php?route=dashboard&action=comment&id=<?= $article['id'] ?>">
                    <input 
                        type="hidden" 
                        name="article-token" 
                        value="<?php foreach($_SESSION['article-tokens'] as $entry):?><?php if($entry['id'] === $article['id']): ?><?=$entry['token'];?><?php endif; ?><?php endforeach; ?>">
                    <input type="hidden" name="article-id" value="<?= $article['id']; ?>">
                    <input type="text" name="comment" placeholder="Écrivez une réponse..."/>
                </form>
            
        </article>
        
        
        <?php endif; ?>
    <?php endforeach; ?>
    
</div>