

    <?php $i = 0; ?>
    <?php foreach($comments as $comment): ?>
        <?php if($comment['article_id'] === $article['id'] && $comment['validate']): ?>
        <?php $i++; ?>
            
            <div class="comment-container">
                
                <a href="index.php?route=profile&user=<?= htmlspecialchars($comment['username']) ?>">
                    <img src="public/uploads/profile_img/<?= $comment['image_path'] = $comment['image_path'] ?? 'default_profile.png'; ?>" alt="Photo de <?= htmlspecialchars($comment['username']) ?>"></img>
                </a>
                <div class="comment-sub-container">
                    <div class="comment">
                        <div class="comment-head">
                            <p><a href="index.php?route=profile&user=<?= htmlspecialchars($comment['username']) ?>"><?= htmlspecialchars($comment['username']) ?></a></p>
                        </div>
                        
                        <p><?= htmlspecialchars($comment['content']) ?></p>
                    </div>
                    <time datetime="<?= htmlspecialchars($comment['time_stamp']) ?>"><?= htmlspecialchars($comment['time_stamp']) ?></time> 
                </div>
                
                <?php if($_SESSION['user_data']['username'] === $article['username'] || $_SESSION['user_data']['username'] === $comment['username'] || $_SESSION['user_data']['validate'] === 5): ?>
                    
                    <form method="post" action="index.php?route=dashboard&action=delete-comment">
                        <input type="hidden" name="comment-id" value="<?=$comment['id'] ?>"/>
                        <input type="hidden" name="comment-token" value="<?php foreach($_SESSION['comment-tokens'] as $entry):?><?php if($entry['id'] === $comment['id']): ?><?=$entry['token'];?><?php endif; ?><?php endforeach; ?>">
                        <button type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" /></svg>
                        </button>
                    </form> 
                    
                <?php endif; ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if($i >= 3 && !isset($allComments)): ?>
        <div class="display-comment"  >
            <p id="button-<?=$article['id']?>">Afficher tous les commentaires</p>
        </div>
    <?php endif;?>

