<h3>Créer un compte</h3>

<form action"index.php" method="post">
    <input type="text" name="register-username" placeholder="Pseudo"/>
    <input type="text" name="register-email" placeholder="E-mail"/>
    <input type="password" name="register-password" placeholder="Mot de passe"/>
    <input type="password" name="register-password-check" placeholder="Comfimez le mot de passe"/>
    <input type="submit" name="Se connecter"/>
</form>

<p>ou</p>

<a href="index.php?route=welcome&action=login">J'ai déjà un compte</a>