<link rel="stylesheet" href="car.css" type="text/css" />

<div id="car-city-app">
    <div class="car-city-container">
        <div class="radio-controller">
            <button id="rc-up">Up</button>
            <button id="rc-down">Down</button>
            <button id="rc-left">Left</button>
            <button id="rc-right">Right</button>
            <button id="rc-swap" class="none">Shift</button>
        </div>
        <div class="car-city-map">
            <div class="car-slot">
                <div class="car panda">
                    <div class="headlights">
                        <div class="headlight headlight-panda"></div>
                        <div class="headlight headlight-panda"></div>
                    </div>
                    <div class="pare-brise">
                        <div class="pare-brise-av"></div>
                        <div class="pare-brise-ar"></div>
                    </div>
                    <div class="rearlights">
                        <div class="rearlight rearlight-panda"></div>
                        <div class="rearlight rearlight-panda"></div>
                    </div>
                </div>
                <div class="car punto">
                    <div class="headlights">
                        <div class="headlight headlight-punto"></div>
                        <div class="headlight headlight-punto"></div>
                    </div>
                    <div class="pare-brise">
                        <div class="pare-brise-av"></div>
                        <div class="pare-brise-ar"></div>
                    </div>
                    <div class="rearlights">
                        <div class="rearlight rearlight-punto"></div>
                        <div class="rearlight rearlight-punto"></div>
                    </div>
                </div>
                <div class="car punto2">
                    <div class="headlights">
                        <div class="headlight headlight-punto"></div>
                        <div class="headlight headlight-punto"></div>
                    </div>
                    <div class="pare-brise">
                        <div class="pare-brise-av"></div>
                        <div class="pare-brise-ar"></div>
                    </div>
                    <div class="rearlights">
                        <div class="rearlight rearlight-punto"></div>
                        <div class="rearlight rearlight-punto"></div>
                    </div>
                </div>
            </div>
            <div class="human">
            </div>
            <div class="wall-slot">
            </div>
            <div class="end-game none">
                <h3>WASTED</h3>
                <p>Vous vous êtes pris un mur...</p>
                <p>
                    <em>(ouch)</em>
                </p>
                <button id="reload-button">Restart</button>
            </div>
        </div>
    </div>
</div>

<script type="module" src="main.js"></script>
