<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css" type="text/css" />
    <title>Pioupiou 2.0</title>
</head>
    <body>
        <header>
            <h1>
                <a href="index.php?route=dashboard">
                    Pioupiou
                </a>
            </h1>
            <?php if(isset($_SESSION['connected'])): ?>
            <nav>
                <a href="index.php?route=profil">Profil</a>
                <a href="index.php?route=disconnect">Deco</a>
            </nav>
            <?php endif; ?>
        </header>
        <main>
            <?php include $template ?>
        </main>
        <footer>
        </footer>
    </body>
</html>